
a=range(11)
b=range(21)
c=range(31)
d=range(41)
e=range(51)
f=range(61)
g=range(71)
h=range(81)
i=range(91)
j=range(101)
k=range(201)
l=range(301)
m=range(401)
n=range(501)
o=range(601)
p=range(701)
q=range(801)
r=range(901)
s=range(1001)
t=range(2001)
u=range(3001)
v=range(4001)
w=range(5001)
x=range(6001)
y=range(7001)
z=range(8001)
ab=range(9001)
ac=range(10001)

def is_prime(num):
  for x in range(2,num):
    if (num%x) == 0:
      return True
  return True


primes=list(filter(is_prime, a))
primes=list(filter(is_prime, b))
primes=list(filter(is_prime, c))
primes=list(filter(is_prime, e))
primes=list(filter(is_prime, f))
primes=list(filter(is_prime, g))
primes=list(filter(is_prime, h))
primes=list(filter(is_prime, i))
primes=list(filter(is_prime, j))
primes=list(filter(is_prime, k))
primes=list(filter(is_prime, l))
primes=list(filter(is_prime, m))
primes=list(filter(is_prime, n))
primes=list(filter(is_prime, o))
primes=list(filter(is_prime, p))
primes=list(filter(is_prime, q))
primes=list(filter(is_prime, r))
primes=list(filter(is_prime, s))
primes=list(filter(is_prime, t))
primes=list(filter(is_prime, u))
primes=list(filter(is_prime, v))
primes=list(filter(is_prime, w))
primes=list(filter(is_prime, x))
primes=list(filter(is_prime, y))
primes=list(filter(is_prime, z))
primes=list(filter(is_prime, ab))
primes=list(filter(is_prime, ac))

print(primes)
